mysql:
  #dns: root:123456@tcp(172.17.0.2:3306)/ginchat?charset=utf8&parseTime=True&loc=Local
  dns: root:123456@tcp(172.17.0.2:3306)/ginchat?charset=utf8mb4&parseTime=True&loc=Local
  
timeout:
  DelayHeartbeat: 3   #延迟心跳时间  单位秒
  HeartbeatHz: 30   #每隔多少秒心跳时间   
  HeartbeatMaxTime: 30000  #最大心跳时间  ，超过此就下线 
  RedisOnlineTime: 4  #缓存的在线用户时长   单位H
udp: 3001